# Generated by Django 4.1.7 on 2023-04-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0007_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='exemplaire',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.CharField(choices=[('P', 'Pret'), ('H-P', 'Hors-Pret')], default='P', max_length=30),
        ),
    ]
