# Generated by Django 4.2 on 2023-04-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
        ('bibliotheque', '0008_remove_book_price_book_exemplaire_book_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
