# Generated by Django 4.1.7 on 2023-04-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bibliotheque', '0005_book_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
